id: sonarqube
backend:
  executable: mattermost-plugin-sonarqube
name: SonarQube
description: Receives webhook events from SoanrQube and makes Mattermost posts for them.
version: '0.1.0'
settings_schema:
  settings:
    - key: Enabled
      display_name: Enable SonarQube Plugin
      type: bool
      help_text: >
        When true, you can configure SonarQube webhooks to post message in Mattermost. 
        To help combat phishing attacks, all posts are labelled by a BOT tag.
    - key: UserName
      display_name: User
      type: username
      help_text: >
        Select the username that this integration is attached to.
    - key: Secret
      display_name: Secret
      type: generated
      help_text: >
        This secret is used to authenticate to Mattermost. 
        regenerate_help_text: Regenerates the secret for the webhook URL endpoint. 
        Regenerating the secret invalidates your existing SoanrQube integrations.
  footer: |
    ここに使い方の説明を書きたい。
    てすと
